- name: Print Parameter store
  hosts: localhost
  tasks:
   - name: Print a parameter
     ansible.builtin.debug:
        msg: "{{ lookup('aws_ssm', 'param_dev_catalogue_MONGO' ,  region='us-east-1') }}"