- name: Demo on vars on play level
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Demo on vars on task level
  hosts: localhost
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
          URL: task.example.com

- name: Demo on vars from file on play level
  hosts: localhost
  vars_files: # file level
   - sample-vars.yml #from file to file ie sample to var file
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
