- name: Demo on vars on play level
  hosts: localhost
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Demo on vars on task level
  hosts: localhost
  connection: local
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
          URL: task.example.com

- name: Demo on vars from file on play level
  hosts: localhost
  connection: local
  vars_files: # file
   - sample.yml #from file to file ie sample to var file
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: vars from inventory file
  hosts: localhost
  connection: local
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Access Facts
  hosts: localhost
  connection: local
  #gather_facts: false
  tasks:
    - name: Print FACT
      ansible.builtin.debug:
        msg: HOSTNAME = {{ansible_hostname}}

- name: Demo on Runtime variable
  hosts: localhost
  connection: local
  #gather_facts: false
  tasks:
    - name: Execute uptime shell command #run time variable
      ansible.builtin.shell: uptime
      register: out

    - name: Set a fact #run time variable
      ansible.builtin.set_fact: #set a variable using fact
         uptime: "{{out.stdout}}"

    - name: Print out #run time variable
      ansible.builtin.debug:
        #uptime: "{{out.stdout}}"
        msg: "{{out.stdout}}"

- name: vars from Roles
  hosts: localhost
  connection: local
  roles:
    -sample
