- name: Demo on vars on play level
  hosts: localhost
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Demo on vars on task level
  hosts: all
  connection: local
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
          URL: task.example.com

- name: Demo on vars from file on play level
  hosts: all
  connection: local
  vars_files: # file
   - sample.yml #from file to file ie sample to var file
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: vars from inventory level
  hosts: all
  connection: local
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}